<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.luna</groupId>
        <artifactId>TogetherChat</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>message-server</artifactId>
    <name>message-server</name>
    <description>Chat Message Server Parent Module for TogetherChat Microservices</description>
    <packaging>pom</packaging>

    <!-- 子模块 -->
    <modules>
        <module>message-server-core</module>
        <module>message-server-api</module>
    </modules>

</project>